### ISSUE TITLE
[Bug 上报] DropMenuItem 组件的外部class没有加到元素上（无效）

### ISSUE THREAD

**Issue by bibinocode** [Moonofweisheng/wot-design-uni#1119]
### Wot UI 版本号

1.9.1

### 平台

h5

### 复现Demo地址（如不提供，将被直接关闭）

无，

### 重现步骤

```html
 <view class="filter-box-left">
    <wd-drop-menu>
        <wd-drop-menu-item custom-title="custom-title" custom-icon="custom-icon" title="筛选"
            ref="dropMenu" icon="caret-down-small" icon-size="64rpx">
            <view>
                111
            </view>
        </wd-drop-menu-item>
    </wd-drop-menu>
</view>
```

```css
.filter-box {
    width: 100%;
    display: flex;
    justify-content: space-between;
    height: 88rpx;




    &-left {
        display: flex;
        flex: 1;
        align-items: center;
        justify-content: space-between;

        :deep(.wd-drop-menu__item-title-text) {
            color: #000;
            font-family: "PingFang SC";
            font-size: 28rpx;
            font-style: normal;
            font-weight: 400;
        }


        :deep(.wd-drop-menu__arrow) {
            color: #999999;
            flex-shrink: 0;
            font-size: 34rpx;
            right: -20rpx;
        }

    }
}
```

![Image](https://github.com/user-attachments/assets/5d8e27d4-9818-4e4d-b7ba-1497a3cab150)

![Image](https://github.com/user-attachments/assets/c355d872-b649-4ec0-af2f-806189d28734)

### 期望的结果是什么？

需要将对应的custom-class 加到对应元素容器上

### 实际的结果是什么？

没有将对应的custom-class 加到对应元素容器上
